                                    Madari
What is it ?
------------
Madari is a traffic shaping software that uses iproute2 utilities , "tc" and "iptables" to shape the traffic and control
the bandwidth allocation to websites based on ip addresses. It is written in python 2.7.

Version :
--------
1.0 Beta.

Dependencies :
-------------
It requires Linux kernel 2.4+ compiled with iproute2, Python 2.7 and yaml, python_crontab python libraries.

How to use it? / Installation :
-------------------------------
Madari doesn't require installation. manager.py is the only file that can be run by the user. It requires root access.
For installing YAML libraries install run this commands if you are in the software home directory:
    cd PyYAML
    sudo python setup.py install
For installing PyCrontab :
    cd python-crontab-1.2
    sudo python setup.py install
It reads the default configuration file written in YAML and generates shell scripts in the directory specified(in "manager.py"). 
It doesn't require any argument by default but if "stop" is specified, the shell scripts generated by madari will be deleted and
default qdisc is changed back to pfifo_fast.
Check the example configuration file for the format that needs to be followed in the configurations file.
Note that you can control only out bound traffic through an interface.

Authors :
---------
U Shiva Teja Reddy (u_shivatejau@students.iitmandi.ac.in)
Akshay Sharma
Surendra Anuragi
Prakhar Agarwal
